spring.application.name=fitbeat

spring.datasource.url=jdbc:postgresql://localhost:5433/gymtrack
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

app.cors.allowed-origins=http://localhost:5173

server.error.include-message=always
